name: restaurant_app
description: "Submission for Dicoding Flutter Fundamental Course"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.2
  flutter_native_splash: ^2.4.6
  flutter_slidable: ^4.0.1
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  flutter_timezone: ^5.0.0
  google_fonts: ^6.3.1
  http: ^1.5.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  readmore: ^3.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1
  workmanager: ^0.9.0+3

dev_dependencies:
  build_runner: ^2.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  mockito: ^5.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/vectors/
